spring:
  application:
    name: merchandise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://rm-wz914f1tfy2x2191ndo.mysql.rds.aliyuncs.com:3306/pistachio
    url: jdbc:mysql://www.singlecycle.biz:3306/db_role_00
    username: singlecycle
    password: singlecycle
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: 数据库连接池--Hikari
      connection-timeout: 5000
      login-timeout: 5000
      validation-timeout: 10000
      auto-commit: true
server:
  address: localhost
  port: 1102
  server-header: brand
eureka:
  instance:
    instance-id: ${spring.application.name}
    appname: ${spring.application.name}
    hostname: pistachio
    initial-status: up
  client:
    service-url:
      defaultZone: http://${server.address}:1100/eureka