apiVersion: v1
kind: Endpoints
metadata:
  name: jenkins
  namespace: service-ci
  labels:
    deployment.ci.name: jenkins
    deployment.ci.env: all
  clusterName: service-ci-master
subsets:
  - addresses:
      - ip: 192.168.1.254
    ports:
      - port: 1025