spring:
  application:
    name: gateway
server:
  port: 1025
  address: localhost
  server-header: brand
eureka:
  instance:
    instance-id: gateway-0
    appname: gateway
    hostname: pistachio
    ip-address: 127.0.0.1
    prefer-ip-address: true
    home-page-url: http://${server.address}:${server.port}/homePage
    health-check-url: http://${server.address}:${server.port}/healthCheck
    initial-status: up
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 60
    registry:
      expected-number-of-renews-per-min: 5
  server:
    enable-self-preservation: false
  client:
    service-url:
#      defaultZone: http://${server.address}:${server.port}/eureka
      defaultZone: http://${server.address}:${server.port}/registrationCenter_0,http://${server.address}:${server.port}/registrationCenter_1
#      backupZone: http://${server.address}:${server.port}/registrationCenter_1
    enabled: true
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 30
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-service-url-poll-interval-seconds: 30