apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx
    env: pro
  ports:
    - port: 8080
      targetPort: 80
      name: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    deployment.name: nginx
    deployment.env: pro
spec:
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        env: pro
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx
      env: pro