spring:
  application:
    name: registrationCenter
server:
  address: localhost
  port: 1024
eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${server.address}:${server.port}/registrationCenter0,http://${server.address}:${server.port}/registrationCenter1