spring:
  application:
    name: registrationCenter
server:
  address: localhost
  port: 1024
eureka:
  server:
    enable-self-preservation: true
  client:
    service-url:
      defaultZone: http://${server.address}:${server.port}/eureka
    enabled: true
    register-with-eureka: false
    fetch-registry: false
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-service-url-poll-interval-seconds: 30