apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-ci-data
  namespace: volume-ci
  labels:
    volume.ci.name: jenkins-data
    volume.ci.env: all
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/data/jenkins
    type: DirectoryOrCreate