apiVersion: v1
kind: Service
metadata:
  name: service-ci-jenkins
  namespace: service-ci
  clusterName: service-ci-jenkins-master
  labels:
    service.ci.name: jenkins
    service.ci.env: all
spec:
  selector:
    deployment.ci.name: jenkins
    deployment.ci.env: all
  ports:
    - port: 30000
      targetPort: 30000
      nodePort: 30000
      name: jenkins
      protocol: TCP
  type: NodePort
  clusterIP: 192.168.255.254
  publishNotReadyAddresses: false
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600