########
# Dockerfile for gateway
# 1. Build with: docker image build -t gateway
# 2. Run with: docker run  --name gateway --hostname gateway -d -v /tmp/logs:/opt/logs -p 1025:1025
# MAINTAINER 单曲循环<1019844337@qq.com>（已经弃用，高版本使用Label指令来设置）
# There can only be one CMD instruction in a Dockerfile. If you list more than one CMD then only the last CMD will take effect.
# HEALTHCHECK OPTIONS CMD command，HEALTHCHECK使用方式（exit code：0，success；1，unhealthy；3，reserved，一般不要使用）
######## 解析器指令格式：#escape=\

ARG RegistryAddress=localhost:65535
ARG ApplicationName=gateway
ARG Version=0.0.1
ARG Port=1025

FROM ${RegistryAddress}/jdk:1.8
ADD ./${ApplicationName}-${Version}.jar /build/jar/gateway

LABEL maintainer="单曲循环（1019844337@qq.com）"
LABEL application.name=${ApplicationName}
LABEL application.version=${Version}
LABEL application.description="网关"

EXPOSE ${Port}/tcp